set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m0plus)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(NOT DEFINED ARM_NONE_EABI_PREFIX)
    set(ARM_NONE_EABI_PREFIX arm-none-eabi)
endif()

set(CMAKE_C_COMPILER ${ARM_NONE_EABI_PREFIX}-gcc)


set(CMAKE_AR      ${ARM_NONE_EABI_PREFIX}-ar)
set(CMAKE_OBJCOPY ${ARM_NONE_EABI_PREFIX}-objcopy CACHE FILEPATH "" FORCE)
set(CMAKE_OBJDUMP ${ARM_NONE_EABI_PREFIX}-objdump CACHE FILEPATH "" FORCE)
set(CMAKE_SIZE    ${ARM_NONE_EABI_PREFIX}-size CACHE FILEPATH "" FORCE)

set(MCPU_FLAGS "-mcpu=cortex-m0plus -mthumb")
set(CMAKE_C_FLAGS_INIT "${MCPU_FLAGS}")

set(CMAKE_EXECUTABLE_SUFFIX ".elf")